# Generated by Django 2.1.4 on 2018-12-29 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("invoices", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="sender",
            field=models.ForeignKey(
                default="01a42646-93f3-42c9-880b-6ddc2cbf4ae8",
                on_delete=django.db.models.deletion.PROTECT,
                to="invoices.Sender",
                verbose_name="Sender",
            ),
            preserve_default=False,
        )
    ]
