# Generated by Django 2.1.4 on 2018-12-29 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_invoice_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='sender',
            name='code',
            field=models.CharField(default='AAAAAAA', max_length=7, verbose_name='Sender code'),
            preserve_default=False,
        ),
    ]
