# Generated by Django 2.1.4 on 2018-12-29 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("invoices", "0006_auto_20181229_2231")]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="causal",
            field=models.TextField(blank=True, verbose_name="Causal"),
        )
    ]
