# Generated by Django 2.1.4 on 2018-12-30 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("invoices", "0009_invoice_invoice_summary")]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="recipient_first_name",
            field=models.CharField(
                blank=True, max_length=60, verbose_name="Recipient first name"
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="recipient_last_name",
            field=models.CharField(
                blank=True, max_length=60, verbose_name="Recipient last name"
            ),
        ),
        migrations.AlterField(
            model_name="sender",
            name="company_name",
            field=models.CharField(max_length=80, verbose_name="Company Name"),
        ),
    ]
