# Generated by Django 2.1.4 on 2019-01-03 17:28

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import invoices.utils


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0011_auto_20181230_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Invoice amount'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.IntegerField(verbose_name='Invoice number'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_summary',
            field=django.contrib.postgres.fields.jsonb.JSONField(validators=[invoices.utils.JSONSchemaValidator({'$schema': 'http://json-schema.org/draft-04/schema#', 'items': [{'properties': {'description': {'type': 'string'}, 'quantity': {'type': 'number'}, 'row': {'type': 'integer'}, 'total_price': {'type': 'number'}, 'unit_price': {'type': 'number'}, 'vat_rate': {'type': 'number'}}, 'required': ['row', 'description', 'quantity', 'unit_price', 'total_price', 'vat_rate'], 'type': 'object'}], 'type': 'array'})]),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_tax_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Invoice tax'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_tax_rate',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Invoice tax rate'),
        ),
    ]
