# Generated by Django 2.1.4 on 2019-01-09 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('invoices', '0014_item'), ('invoices', '0015_auto_20190105_1435'), ('invoices', '0016_auto_20190105_1438'), ('invoices', '0017_remove_invoice_invoice_summary'), ('invoices', '0018_auto_20190105_1807'), ('invoices', '0019_auto_20190109_1624'), ('invoices', '0020_auto_20190109_1631')]

    dependencies = [
        ('invoices', '0013_auto_20190105_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.SmallIntegerField(verbose_name='Item number')),
                ('description', models.CharField(max_length=128, verbose_name='Description')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Unit price')),
                ('vat_rate', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Tax')),
            ],
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='invoice_summary',
        ),
        migrations.AddField(
            model_name='item',
            name='invoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoices.Invoice'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(max_length=8, verbose_name='Invoice number'),
        ),
    ]
