# Generated by Django 2.1.7 on 2019-02-17 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("invoices", "0015_sender_user")]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="invoice_number",
            field=models.CharField(
                max_length=20, verbose_name="Invoice number"
            ),
        )
    ]
