# Generated by Django 2.1.5 on 2019-02-10 19:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("invoices", "0016_invoice_payment_method")]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="invoice_deadline",
            field=models.DateField(
                default=datetime.date(2019, 2, 10),
                verbose_name="Invoice deadline",
            ),
            preserve_default=False,
        )
    ]
