# Generated by Django 2.1.7 on 2019-02-17 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0017_invoice_invoice_deadline"),
        ("invoices", "0016_auto_20190217_2010"),
    ]

    operations = []
