# Generated by Django 2.1.7 on 2019-02-12 22:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0017_invoice_invoice_deadline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Retention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('retention_type', models.CharField(choices=[('RT01', 'Ritenuta persone fisiche'), ('RT02', 'Ritenuta persone giuridiche')], max_length=4, verbose_name='Retention type')),
                ('retention_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Retention amount')),
                ('retention_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Retention rate')),
                ('retention_causal', models.CharField(choices=[('A', 'Prestazioni di lavoro autonomo rientranti nell’esercizio di arte o professione abituale.'), ('B', 'Utilizzazione economica, da parte dell’autore o dell’inventore, di opere dell’ingegno, di brevetti industriali e di processi, formule o informazioni relativi a esperienze acquisite in campo industriale, commerciale o scientifico.'), ('C', 'Utili derivanti da contratti di associazione in partecipazione e da contratti di cointeressenza, quando l’apporto è costituito esclusivamente dalla prestazione di lavoro.'), ('D', 'Utili spettanti ai soci promotori e ai soci fondatori delle società di capitali.'), ('E', 'Levata di protesti cambiari da parte dei segretari comunali.'), ('G', 'Indennità corrisposte per la cessazione di attività sportiva professionale.'), ('H', 'Indennità corrisposte per la cessazione dei rapporti di agenzia delle persone fisiche e delle società di persone, con esclusione delle somme maturate entro il 31.12.2003, già imputate per competenza e tassate come reddito d’impresa.'), ('I', 'Indennità corrisposte per la cessazione da funzioni notarili.'), ('L', 'Utilizzazione economica, da parte di soggetto diverso dall’autore o dall’inventore, di opere dell’ingegno, di brevetti industriali e di processi, formule e informazioni relative a esperienze acquisite in campo industriale, commerciale o scientifico.'), ('L1', 'Utilizzazione economica, da parte di soggetto diverso dall’autore o dall’inventore, di opere dell’ingegno, di brevetti industriali e di processi, formule e informazioni relative a esperienze acquisite in campo industriale, commerciale o scientifico.'), ('M', 'Prestazioni di lavoro autonomo non esercitate abitualmente, obblighi di fare, di non fare o permettere.'), ('M1', 'Prestazioni di lavoro autonomo non esercitate abitualmente, obblighi di fare, di non fare o permettere.'), ('N', 'Indennità di trasferta, rimborso forfetario di spese, premi e compensi erogati: .. nell’esercizio diretto di attività sportive dilettantistiche'), ('O', 'Prestazioni di lavoro autonomo non esercitate abitualmente, obblighi di fare, di non fare o permettere, per le quali non sussiste l’obbligo di iscrizione alla gestione separata (Circ. Inps 104/2001).'), ('O1', 'Prestazioni di lavoro autonomo non esercitate abitualmente, obblighi di fare, di non fare o permettere, per le quali non sussiste l’obbligo di iscrizione alla gestione separata (Circ. Inps 104/2001).'), ('P', 'Compensi corrisposti a soggetti non residenti privi di stabile organizzazione per l’uso o la concessione in uso di attrezzature industriali, commerciali o scientifiche che si trovano nel territorio dello'), ('Q', 'Provvigioni corrisposte ad agente o rappresentante di commercio monomandatario.'), ('R', 'Provvigioni corrisposte ad agente o rappresentante di commercio plurimandatario.'), ('S', 'Provvigioni corrisposte a commissionario.'), ('T', 'Provvigioni corrisposte a mediatore.'), ('U', 'Provvigioni corrisposte a procacciatore di affari.'), ('V', 'Provvigioni corrisposte a incaricato per le vendite a domicilio e provvigioni corrisposte a incaricato per la vendita porta a porta e per la vendita ambulante di giornali quotidiani e periodici (L. 25.02.1987, n. 67).'), ('W', 'Corrispettivi erogati nel 2013 per prestazioni relative a contratti d’appalto cui si sono resi applicabili le disposizioni contenute nell’art. 25-ter D.P.R. 600/1973.'), ('X', 'Canoni corrisposti nel 2004 da società o enti residenti, ovvero da stabili organizzazioni di società estere di cui all’art. 26-quater, c. 1, lett. a) e b) D.P.R. 600/1973, a società o stabili organizzazioni di società, situate in altro Stato membro dell’Unione Europea in presenza dei relativi requisiti richiesti, per i quali è stato effettuato nel 2006 il rimborso della ritenuta ai sensi dell’art. 4 D. Lgs. 143/2005.'), ('Y', 'Canoni corrisposti dal 1.01.2005 al 26.07.2005 da soggetti di cui al punto precedente.'), ('Z', 'Titolo diverso dai precedenti.')], max_length=2, verbose_name='Causal')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WelfareFund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('welfare_type', models.CharField(choices=[('TC01', 'Cassa nazionale previdenza e assistenza avvocati e procuratori legali'), ('TC02', 'Cassa previdenza dottori commercialisti'), ('TC03', 'Cassa previdenza e assistenza geometri'), ('TC04', 'Cassa nazionale previdenza e assistenza ingegneri e architetti liberi professionisti'), ('TC05', 'Cassa nazionale del notariato'), ('TC06', 'Cassa nazionale previdenza e assistenza ragionieri e periti commerciali'), ('TC07', 'Ente nazionale assistenza agenti e rappresentanti di commercio (ENASARCO)'), ('TC08', 'Ente nazionale previdenza e assistenza consulenti del lavoro (ENPACL)'), ('TC09', 'Ente nazionale previdenza e assistenza medici (ENPAM)'), ('TC10', 'Ente nazionale previdenza e assistenza farmacisti (ENPAF)'), ('TC11', 'Ente nazionale previdenza e assistenza veterinari (ENPAV)'), ('TC12', "Ente nazionale previdenza e assistenza impiegati dell'agricoltura (ENPAIA)"), ('TC13', 'Fondo previdenza impiegati imprese di spedizione e agenzie marittime'), ('TC14', 'Istituto nazionale previdenza giornalisti italiani (INPGI)'), ('TC15', 'Opera nazionale assistenza orfani sanitari italiani (ONAOSI)'), ('TC16', 'Cassa autonoma assistenza integrativa giornalisti italiani (CASAGIT)'), ('TC17', 'Ente previdenza periti industriali e periti industriali laureati (EPPI)'), ('TC18', 'Ente previdenza e assistenza pluricategoriale (EPAP)'), ('TC19', 'Ente nazionale previdenza e assistenza biologi (ENPAB)'), ('TC20', 'Ente nazionale previdenza e assistenza professione infermieristica (ENPAPI)'), ('TC21', 'Ente nazionale previdenza e assistenza psicologi (ENPAP)'), ('TC22', 'INPS')], max_length=4, verbose_name='Welfare type')),
                ('welfare_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Welfare rate')),
                ('welfare_contribution', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Welfare contribution')),
                ('welfare_taxable', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Welfare taxable')),
                ('welfare_vat_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Welfare vat rate')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Addresses'},
        ),
        migrations.AddField(
            model_name='invoice',
            name='retention',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='invoices.Retention'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='welfare_fund',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='invoices.WelfareFund'),
        ),
    ]
