# Generated by Django 2.1.7 on 2019-02-25 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("invoices", "0018_merge_20190217_2025")]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="recipient_denomination",
            field=models.CharField(
                blank=True,
                max_length=80,
                verbose_name="Recipient denomination",
            ),
        )
    ]
