# Generated by Django 2.1.7 on 2019-03-15 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("invoices", "0019_invoice_recipient_denomination")]

    operations = [
        migrations.AlterField(
            model_name="sender",
            name="code",
            field=models.CharField(
                max_length=13, verbose_name="Sender VAT Number"
            ),
        )
    ]
