# Generated by Django 2.1.7 on 2019-03-26 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("invoices", "0020_auto_20190315_1640")]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="recipient_code",
            field=models.CharField(
                blank=True, max_length=7, verbose_name="Recipient code"
            ),
        )
    ]
