# Generated by Django 2.1.7 on 2019-05-27 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("invoices", "0021_auto_20190326_2355")]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="recipient_fiscal_code",
            field=models.CharField(
                blank=True, max_length=16, verbose_name="Recipient fiscal code"
            ),
        )
    ]
